const $=id=>document.getElementById(id);const pad=n=>String(n).padStart(2,'0');let format24=localStorage.getItem('clockFormat')!=='12';const zones=[['indiaTime','Asia/Kolkata'],['utcTime','UTC'],['nyTime','America/New_York'],['tokyoTime','Asia/Tokyo']];
function fmt(date,timeZone){return new Intl.DateTimeFormat('en-GB',{timeZone,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:!format24}).format(date)}
function updateRadar(h,m,s,ms){const smoothS=s+ms/1000;const smoothM=m+smoothS/60;const smoothH=(h%12)+smoothM/60;[['hour-clock',smoothH,12,'hourValue',h%12||12],['minute-clock',smoothM,60,'minuteValue',m],['second-clock',smoothS,60,'secondValue',s]].forEach(([id,value,max,label,text])=>{const el=$(id);if(!el)return;const hand=el.querySelector('.radar-hand');hand.style.transform=`translateX(-50%) rotate(${value/max*360}deg)`;$(label).textContent=pad(text)});}
function update(){const now=new Date(),h=now.getHours(),m=now.getMinutes(),s=now.getSeconds(),ms=now.getMilliseconds();const local=Intl.DateTimeFormat().resolvedOptions().timeZone;$('timezone').textContent=local;updateRadar(h,m,s,ms);$('digitalClock').textContent=formatTime(h,m,s);$('ampm').textContent=format24?'24-HOUR MODE':(h<12?'AM':'PM');$('date').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(now);zones.forEach(([id,z])=>$(id).textContent=fmt(now,z));progress(now);telemetry();requestAnimationFrame(update)}
function formatTime(h,m,s){if(format24)return `${pad(h)}:${pad(m)}:${pad(s)}`;return `${pad(h%12||12)}:${pad(m)}:${pad(s)}`}
function pct(v,t){return Math.min(100,Math.max(0,v/t*100))}function progress(now){const ds=new Date(now.getFullYear(),now.getMonth(),now.getDate()),de=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1),ms=new Date(now.getFullYear(),now.getMonth(),1),me=new Date(now.getFullYear(),now.getMonth()+1,1),ys=new Date(now.getFullYear(),0,1),ye=new Date(now.getFullYear()+1,0,1);[['dayProgress','dayPct',pct(now-ds,de-ds)],['monthProgress','monthPct',pct(now-ms,me-ms)],['yearProgress','yearPct',pct(now-ys,ye-ys)]].forEach(([b,l,v])=>{$(b).style.width=`${v}%`;$(`${l}`).textContent=`${v.toFixed(1)}%`})}
function telemetry(){$('network').textContent=navigator.onLine?'ONLINE':'OFFLINE';$('lang').textContent=navigator.language.toUpperCase();$('screen').textContent=`${screen.width}×${screen.height}`;if(navigator.getBattery)navigator.getBattery().then(b=>$('battery').textContent=`${Math.round(b.level*100)}%${b.charging?' ⚡':''}`).catch(()=>{})}
window.addEventListener('online',telemetry);window.addEventListener('offline',telemetry);
let swStart=0,swElapsed=0,swRunning=false,swFrame;function renderSW(){const t=swElapsed+(swRunning?performance.now()-swStart:0),cs=Math.floor(t/10)%100,s=Math.floor(t/1000)%60,m=Math.floor(t/60000)%60,h=Math.floor(t/3600000);$('toolDisplay').textContent=`${pad(h)}:${pad(m)}:${pad(s)}.${pad(cs)}`;if(swRunning)swFrame=requestAnimationFrame(renderSW)}$('startStopwatch').onclick=()=>{if(swRunning){swElapsed+=performance.now()-swStart;swRunning=false;cancelAnimationFrame(swFrame);$('startStopwatch').textContent='START'}else{swStart=performance.now();swRunning=true;$('startStopwatch').textContent='STOP';renderSW()}};$('resetStopwatch').onclick=()=>{swRunning=false;swElapsed=0;cancelAnimationFrame(swFrame);$('startStopwatch').textContent='START';renderSW()};renderSW();
let timer=300,timerRunning=false,timerId;function renderTimer(){const m=Math.floor(timer/60),s=timer%60;$('timerDisplay').textContent=`${pad(m)}:${pad(s)}`}renderTimer();$('timerBtn').onclick=()=>{if(timerRunning){clearInterval(timerId);timerRunning=false;$('timerBtn').textContent='START 5M TIMER';return}if(timer<=0)timer=300;timerRunning=true;$('timerBtn').textContent='STOP TIMER';timerId=setInterval(()=>{timer--;renderTimer();if(timer<=0){clearInterval(timerId);timerRunning=false;$('timerBtn').textContent='START 5M TIMER';beep()}},1000)};function beep(){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.value=.08;o.start();o.stop(c.currentTime+.4)}catch(e){}}
const quotes=['The people who are crazy enough to think they can change the world are the ones who do.','TIME IS A RESOURCE. USE IT.','PROGRESS > PERFECTION.','BUILD. BREAK. LEARN. REPEAT.'];let qi=0,ci=0;function type(){const q=quotes[qi];$('quoteText').textContent=q.slice(0,ci++);if(ci>q.length){setTimeout(()=>{ci=0;qi=(qi+1)%quotes.length;type()},1800);return}setTimeout(type,55)}type();
const canvas=$('matrix'),ctx=canvas.getContext('2d');let drops=[],font=12,intensity=3;function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);drops=Array(Math.ceil(r.width/font)).fill(1)}window.addEventListener('resize',resize);resize();function matrix(){const r=canvas.getBoundingClientRect();ctx.fillStyle='rgba(0,0,0,.13)';ctx.fillRect(0,0,r.width,r.height);ctx.font=`${font}px monospace`;for(let i=0;i<drops.length;i++){if(Math.random()>.18*intensity)continue;ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--green');ctx.fillText(Math.random().toString(36).slice(2,3).toUpperCase(),i*font,drops[i]*font);if(drops[i]*font>r.height&&Math.random()>.96)drops[i]=0;drops[i]++}}setInterval(matrix,55);
$('settingsBtn').onclick=()=>$('settings').classList.add('open');$('closeSettings').onclick=()=>$('settings').classList.remove('open');$('settings').onclick=e=>{if(e.target===$('settings'))$('settings').classList.remove('open')};$('matrixRange').oninput=e=>intensity=+e.target.value;$('format').value=format24?'24':'12';$('format').onchange=e=>{format24=e.target.value==='24';localStorage.setItem('clockFormat',format24?'24':'12')};$('themeBtn').onclick=()=>document.body.classList.toggle('amber');$('fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();update();